# docker-compose.yml

version: '3.8'
services:
  nest:
    image: nest/bankroot:v1
    restart: always
    ports:
      - '3000:3000'
    networks:
      - postgres-network
    environment:
      - DATABASE_URL=postgres://root:strong@postgres:5432/bankroot
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=strong
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
        - postgres-network

volumes:
  postgres:

networks:
 postgres-network:
   driver: bridge