name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send files to server
      uses: appleboy/scp-action@master
      with:
        host: 152.228.163.78
        username: debian
        password: ${{ secrets.SERVER_PASSWORD }}
        source: src/back/
        target: bankroot

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: 152.228.163.78
        username: debian
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /home/debian/bankroot/src/back
          docker build -t nest/bankroot:v1 .
          docker-compose up -d
