name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my_image .

    - name: Test Docker image
      run: docker run my_image npm test

    - name: Send files to server
      uses: appleboy/scp-action@master
      with:
        host: 152.228.163.78
        username: debian
        password: ${{ secrets.SERVER_PASSWORD }}
        source: src/back/
        target: /home/your_username/

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: 152.228.163.78
        username: debian
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /home/your_username/src/back
          docker-compose up -d
